### DISCUSSION TITLE
Cant detect kasa plugs on network.

### DISCUSSION THREAD

**Discussion by alexsahka** [cbpowell/SenseLink#16] [Q&A]
I was playing with the docker container (https://github.com/cbpowell/SenseLink/blob/master/docker-compose.yml) for the last 3 days.  Here is my config file:

```
sources:
# MQTT
- mqtt:
    host: "10.xx.xx.xx"
    port: 1883
    username: xxxx
    password: xxxxxx
    plugs:
        - Posts_Lights:
            alias: "Posts Lights"
            mac: 53:75:31:f6:4d:00
            max_watts: 80
            state_topic: barrels_light_control/gpio03/state
            on_state_value: "1"
            off_state_value: "0"
```

Trying to detect this "virtual plug" on the network with NodeRed or Sense but can't find any plugs on my network.
Here is the log from docker:
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}
WARNING:root:Unexpected/unhandled message: {'system': {'get_sysinfo': {}}}

 Is this a normal log?
