### DISCUSSION TITLE
Got senseLink working with Shelly EM

### DISCUSSION THREAD

**Discussion by kevinismith** [cbpowell/SenseLink#24] [Show and tell]
Hi, I have SenseLink working with Shelly energy monitoring (https://www.shelly.com/en-us/products/energy-metering#unfiltered)

It took me a while to get it working. In particular, getting the yml setup correctly esp since it requires a keypath (which I don't think it well documented) and the keypath needs to be specific to the Shelly JSON message. (Also, the Shelly device needs to be setup properly and the yml needs to match it.)

Anyway, I'd love to contribute back but I don't know the best way to do this.

There seem to be 2 parts to getting this to work
1) SenseLink setup (the yml)
2) Stuff outside of SenseLink. (Like setting up an MQTT broker and setting up the Shelly)

Should I edit the README? Or try to add this to the example YML? Go post to reddit? Or something else?

I love SenseLink - I really appreciate it. I feel like if I contribute some docs / info this can reach even more people.

**Comment by kevinismith** [comment]
Here's a followup to try to capture what I've done.

**Complete system**
1) A Shelly energy meter setup to publish to MQTT. (https://www.shelly.com/en-us/products/energy-metering)
2) A Raspberry pi running a MQTT broker
3) The same raspberry pi running SenseLink.

    Note: There are lots of viable variations (like not using a raspberry pi) but this is the one I'll go over.

**Setup**
1) The Shelly needs MQTT enabled, this is done via the Shelly WebUI. See the Shelly docs for basics but here are the specifics.
   You want "Generic status update over MQTT" turned on. This sends more messages and gives a faster update rate.

      **MQTT Prefix:** Set any string you want but you'll need this later to get senseLink properly "listening". EX: "TeslaCharger"
      **IP Address:** Set this to your Raspberry PI's address and add the port 1883. EX: 192.168.86.54:1883
             (Note: Don't forget to make your raspberry pi's IP unchanging. I did this through the "pin" feature in my Google Wifi)
      **ClientID:** Same as the MQTT prefix. (I don't think they need to be the same but might as well...)

2) The Raspberry Pi MQTT broker. I suggest Mosquitto.
     I followed this: 
          https://randomnerdtutorials.com/how-to-install-mosquitto-broker-on-raspberry-pi
          Don't forget to add:
                listener 1883
                allow_anonymous true
     
3) The same raspberry pi running SenseLink.
     Setup SenseLink as per the instructions and add a plug to your config.yml following this format:
          (Note: I wrote this while away from my system so I'm writing this from memory, I need to update it later to make sure it's exactly right.)
```
sources:
- mqtt:
    host: localhost # Assuming mosquitto is running on the same machine
    port: 1883       # Optional
    username: admin  # Optional
    password: supersecret1  # Optional
    plugs:
        # Direct power reporting example
        - TeslaCharger:
            mac: "TeslaCharger" # Interesting note: This is not a mac address format but Sense didn't mind a "string" here.
            alias: "TeslaCharger"
            power_topic: <MQTT Prefix>/status/pm1:0  # Needs to match the "MQTT Prefix" set in the Shelly MQTT config!
            power_topic_keypath: apower # Comes from the Shelly MQTT format;"apower" is the keypath for where Shelly encodes watts.
```

**Debugging:**
    It would be great if this worked the first time but... That's not how it usually goes.
    
**Check if the MQTT messages are coming reaching the MQTT broker.**
     Go to the Raspberry Pi and subscribe to *all* messages. This will show you a) If the messages are being received 2) The formant of the messages.
     Run:  `mosquitto_sub -h localhost -t '#' -v`

You should see something like this : 

```
TeslaCharger/status/pm1:0 {"id":0, "voltage":246.6, "current":0.036, "apower":2.5 ,"freq":41.7,"aenergy":{"total":135.358,"by_minute":[34427.563,40201.130,33144.549],"minute_ts":1707022979},"ret_aenergy":{"total":0.000,"by_minute":[0.000,0.000,0.000],"minute_ts":1707022979}}
plus/debug/log shellyplugus-b48a0a1b54d0 1104 1707022981.318 2|shelly_notification:161 Status change of switch:0: {"id":0,"apower":16.0}
```

The things of note in this message are:
**The topic: "TeslaCharger/status/pm1:0"** This needs to match the plug config in your SenseLink's config.yml. More specifically, it needs to match the "power_topic:" specified for your plug. (This is how SenseLink knows which messages are from which plugs so make sure they match!) Also, note, the topic is composed from the MQTT Prefix you set in the Shelly setup. (So, in the example above, the MQTT Prefix was set to "TeslaCharger".)
**"apower":2.5** This is the section that says the current (no pun intended) power usage (watts). There's clearly lots more data in the message but this is the power portion. This is the part that SenseLink needs to extract from the message so it can pass it on to the sense. The way to configure SenseLink to extract this portion is "power_keypath" in the plug config in the config.yml. Specifically, set "power_keypath: apower". If you see a different format in your message (EX: In the future, Shelly changes the format of the message) then you'll need to alter the keypath.
