### ISSUE TITLE
MQTT JSON Value

### ISSUE THREAD

**Issue by vb543** [cbpowell/SenseLink#22]
Hello!

I'm trying to get a Shelly Plus 1PM to be picked up by SenseLink via MQTT. The Shelly device returns json and I'm not quite sure if it's possible to just pick up on the apower value. 

Config: 

```
sources:
# MQTT
- mqtt:
    host: "10.4.2.120"
    port: 1883       # Optional
    plugs:
        # Direct power reporting example
        - BedroomAC:
            mac: 53:75:31:f6:4d:06
            alias: "Bedroom A/C"
            power_topic: shelly-bedroom-ac/status/switch:0  #
```

MQTT Value at that topic:

```
{"id":0, "source":"init", "output":true, "apower":4.2, "voltage":124.7, "current":0.173, "aenergy":{"total":163.603,"by_minute":[70.165,70.165,70.636],"minute_ts":1687031099},"temperature":{"tC":57.9, "tF":136.3}}
```

"apower" is power usage in watts
